---
# tasks file for nodes
- name: Add route
  lineinfile:
    path: /etc/network/interfaces
    line: "post-up ip route add 10.96.0.1/32 via {{ hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address'] }} dev enp0s8"
  when:
    -  pod_network == "weave"
    -  inventory_hostname in groups['nodes']

- name: Get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  when: inventory_hostname in groups['masters']

- name: Set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
  when: inventory_hostname in groups['masters']

- name: Join cluster
  shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
  when: inventory_hostname in groups['nodes']

- name: Unconditionally reboot K8 nodes
  reboot:
  when: inventory_hostname in groups['nodes']
